# Generated by Django 5.0.7 on 2025-11-30 00:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(choices=[('Auxílio Transporte', 'Auxílio transporte'), ('Auxílio Moradia', 'Auxílio moradia'), ('Alimentação Estudantil', 'Alimentação estudantil'), ('Apoio a Formação Estudantil', 'Apoio a formação estudantil'), ('Auxílios Eventuais', 'Auxílios eventuais'), ('Outros', 'Outros')], default='', max_length=27)),
                ('campus', models.CharField(choices=[('apodi', 'Apodi'), ('caico', 'Caicó'), ('canguaretama', 'Canguaretama'), ('ceara_mirim', 'Ceará-Mirim'), ('currais_novos', 'Currais Novos'), ('ipanguacu', 'Ipanguaçu'), ('joao_camara', 'João Câmara'), ('jucurutu', 'Jucurutu'), ('lajes', 'Lajes'), ('macau', 'Macau'), ('mossoro', 'Mossoró'), ('Natal Central', 'Natal-Central'), ('Natal-Cidade-Alta', 'Cidade Alta'), ('natal_zona_norte', 'Natal-Zona Norte'), ('nova_cruz', 'Nova Cruz'), ('parelhas', 'Parelhas'), ('parnamirim', 'Parnamirim'), ('pau_dos_ferros', 'Pau dos Ferros'), ('santa_cruz', 'Santa Cruz'), ('sao_goncalo', 'São Gonçalo do Amarante'), ('sao_paulo_potengi', 'São Paulo do Potengi')], max_length=100)),
                ('qtd_chamados', models.IntegerField(blank=True, default=0, null=True)),
                ('impedir_aluno', models.BooleanField(default=False)),
                ('exigir_comprov', models.BooleanField(default=False)),
                ('exigir_frequen', models.BooleanField(default=False)),
                ('disponibilidade', models.BooleanField(default=False)),
                ('edital', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auxilio',
            },
        ),
        migrations.CreateModel(
            name='StatusSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'solicitacao_status',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=14, unique=True, verbose_name='Matrícula')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('curso', models.CharField(choices=[('administracao', 'Administração'), ('controle_ambiental', 'Controle Ambiental'), ('edificacoes', 'Edificações'), ('eletrotecnica', 'Eletrotécnica'), ('geologia', 'Geologia'), ('informatica_internet', 'Informática para Internet'), ('manutencao_suporte', 'Manutenção e Suporte em Informática'), ('mecanica', 'Mecânica'), ('mineracao', 'Mineração'), ('controle_ambiental_sub', 'Controle Ambiental (Subsequente)'), ('edificacoes_sub', 'Edificações (Subsequente)'), ('eletrotecnica_sub', 'Eletrotécnica (Subsequente)'), ('geologia_sub', 'Geologia (Subsequente)'), ('mecanica_sub', 'Mecânica (Subsequente)'), ('mineracao_sub', 'Mineração (Subsequente)'), ('petroleo_gas_sub', 'Petróleo e Gás (Subsequente)'), ('redes_comp_sub', 'Redes de Computadores (Subsequente)'), ('manutencao_suporte_sub', 'Manutenção e Suporte em Informática (Subsequente)'), ('informatica_sub', 'Informática (Subsequente)'), ('seguranca_trabalho_sub', 'Segurança do Trabalho (Subsequente)'), ('estradas_sub', 'Estradas (Subsequente)'), ('implanta_voip_fic', 'Implantação de Serviços VoIP (FIC)'), ('aplicador_ceramico_fic', 'Aplicador de Revestimento Cerâmico (FIC)'), ('artesanato_reciclavel_fic', 'Artesanato com Material Reciclável (FIC)'), ('engenharia_civil', 'Engenharia Civil'), ('engenharia_energia', 'Engenharia de Energia'), ('engenharia_sanitaria', 'Engenharia Sanitária e Ambiental'), ('tecnologia_ads', 'Tecnologia em Análise e Desenvolvimento de Sistemas'), ('tecnologia_com_exterior', 'Tecnologia em Comércio Exterior'), ('tecnologia_gestao_publica', 'Tecnologia em Gestão Pública'), ('tecnologia_redes_comp', 'Tecnologia em Redes de Computadores'), ('esp_seguranca_trab', 'Especialização em Engenharia de Segurança do Trabalho'), ('esp_ensino_geociencias', 'Especialização em Ensino de Geociências'), ('esp_gestao_ambiental', 'Especialização em Gestão Ambiental'), ('mestrado_prof_ensino_fis', 'Mestrado Profissional em Ensino de Física'), ('mestrado_prof_recursos_nat', 'Mestrado Profissional em Uso Sustentável de Recursos Naturais'), ('doutorado_educacao_prof', 'Doutorado Acadêmico em Educação Profissional')], max_length=300, verbose_name='Curso')),
                ('periodo', models.IntegerField(verbose_name='Período')),
                ('status', models.CharField(max_length=100)),
                ('campus', models.CharField(default='Natal-Central', max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistenteSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7, unique=True, verbose_name='Matrícula')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistentesocial', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('tipo_de_chamado', models.CharField(choices=[('alteracao_documentos', 'Alteração de documentos'), ('arquivos_pendentes', 'Arquivos pendentes'), ('justificacao', 'Justificação'), ('outro', 'Outro')], default='alteracao de documentos', max_length=25)),
                ('tipo_de_auxilio', models.CharField(choices=[('Auxílio Transporte', 'Auxílio transporte'), ('Auxílio Moradia', 'Auxílio moradia'), ('Alimentação Estudantil', 'Alimentação estudantil'), ('Apoio a Formação Estudantil', 'Apoio a formação estudantil'), ('Auxílios Eventuais', 'Auxílios eventuais'), ('Outros', 'Outros')], default='auxilio transporte', max_length=30)),
                ('status', models.CharField(choices=[('em_analise', 'Em análise'), ('concluido', 'Concluído'), ('fechado', 'Fechado')], max_length=10)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_analise', models.DateField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno', verbose_name='chamados')),
                ('assistente_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assistentesocial', verbose_name='chamados')),
            ],
            options={
                'db_table': 'chamado',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('objetivo', models.TextField()),
                ('solicitados', models.CharField(choices=[('todos', 'Todos os alunos'), ('auxilio', 'Alunos do auxílio selecionado'), ('individual', 'Alunos selecionados individualmente')], default='Todos', max_length=30)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('alunos_solicitados', models.IntegerField(default=0)),
                ('alunos_selecionados', models.ManyToManyField(blank=True, related_name='formularios_individuais', to='api.aluno', verbose_name='Alunos Selecionados')),
                ('auxilio_alvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formularios_alvo', to='api.auxilio', verbose_name='Auxílio Alvo')),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
        migrations.CreateModel(
            name='FormularioQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_pergunta', models.CharField(max_length=250)),
                ('tipo_pergunta', models.CharField(choices=[('paragrafo', 'Parágrafo'), ('multipla_escolha', 'Múltipla escolha'), ('caixa_selecao', 'Caixas de seleção')], default='multipla escolha', max_length=50)),
                ('obrigatoriedade', models.BooleanField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='api.formulario')),
            ],
            options={
                'db_table': 'formulario_questao',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='FormularioQuestaoOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.CharField(max_length=250)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='api.formularioquestao')),
            ],
            options={
                'db_table': 'formulario_questao_opcao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25, null=True)),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('nao_lida', 'Não lida'), ('lida', 'Lida')], max_length=20)),
                ('data_visualizacao', models.DateField(blank=True, null=True)),
                ('usuario', models.ManyToManyField(related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacao',
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=900)),
                ('resposta', models.CharField(blank=True, max_length=900, null=True)),
                ('status', models.CharField(choices=[('respondida', 'Respondida'), ('nao_respondida', 'Não respondida')], max_length=100)),
                ('data_realizacao', models.DateField(auto_now_add=True)),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.aluno')),
                ('assistente_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assistentesocial')),
            ],
            options={
                'db_table': 'pergunta',
            },
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('completo', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.formulario')),
            ],
            options={
                'db_table': 'resposta_formulario',
                'unique_together': {('formulario', 'aluno')},
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_deferimento', models.DateField(blank=True, null=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_aluno', to='api.aluno')),
                ('id_assistente_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_AS', to='api.assistentesocial')),
                ('tipo_auxilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxilio', to='api.auxilio')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='api.statussolicitacao')),
            ],
            options={
                'db_table': 'solicitacao',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('comprovante_residencia', 'Comprovante de residência'), ('historico_escolar', 'Histórico escolar'), ('comprovante_renda', 'Comprovante de renda'), ('comprovante_ausencia_renda', 'Comprovante de ausência de renda'), ('outros', 'Outros')], max_length=35)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.solicitacao')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField()),
                ('data_finalizacao', models.DateField(blank=True, null=True)),
                ('justificativa_finalizacao', models.CharField(blank=True, max_length=200, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficio', to='api.aluno')),
                ('tipo_auxilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficio', to='api.auxilio')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficio', to='api.solicitacao')),
            ],
            options={
                'db_table': 'beneficio',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_aberta', models.TextField(blank=True, null=True)),
                ('opcao_escolhida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.formularioquestaoopcao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formularioquestao')),
                ('resposta_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_questoes', to='api.respostaformulario')),
            ],
            options={
                'db_table': 'resposta_questao',
                'unique_together': {('resposta_formulario', 'questao')},
            },
        ),
    ]
