# Generated by Django 5.0.7 on 2025-12-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxilio',
            name='campus',
        ),
        migrations.AddField(
            model_name='auxilio',
            name='nome',
            field=models.CharField(choices=[('Auxílio Transporte', 'Auxílio transporte'), ('Auxílio Moradia', 'Auxílio moradia'), ('Alimentação Estudantil', 'Alimentação estudantil'), ('Apoio a Formação Estudantil', 'Apoio a formação estudantil'), ('Auxílios Eventuais', 'Auxílios eventuais'), ('Outros', 'Outros')], default='', max_length=27),
        ),
        migrations.AlterField(
            model_name='auxilio',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
