# Generated by Django 5.0.7 on 2025-12-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_auxilio_nome_alter_chamado_tipo_de_auxilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
