# Generated by Django 5.0.7 on 2026-01-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_documento_url_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ingresso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='qtd_periodos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
