# Generated by Django 5.0.7 on 2026-01-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_documento_titulo_alter_notificacao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxilio',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
