# Generated by Django 5.0.7 on 2026-01-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_auxilio_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxilio',
            name='campus',
            field=models.CharField(choices=[('apodi', 'Apodi'), ('caico', 'Caicó'), ('canguaretama', 'Canguaretama'), ('ceara_mirim', 'Ceará-Mirim'), ('currais_novos', 'Currais Novos'), ('ipanguacu', 'Ipanguaçu'), ('joao_camara', 'João Câmara'), ('jucurutu', 'Jucurutu'), ('lajes', 'Lajes'), ('macau', 'Macau'), ('mossoro', 'Mossoró'), ('Natal Central', 'Natal-Central'), ('Natal-Cidade-Alta', 'Cidade Alta'), ('natal_zona_norte', 'Natal-Zona Norte'), ('nova_cruz', 'Nova Cruz'), ('parelhas', 'Parelhas'), ('parnamirim', 'Parnamirim'), ('pau_dos_ferros', 'Pau dos Ferros'), ('santa_cruz', 'Santa Cruz'), ('sao_goncalo', 'São Gonçalo do Amarante'), ('sao_paulo_potengi', 'São Paulo do Potengi')], default='', max_length=100),
        ),
    ]
