# Generated by Django 5.0.7 on 2026-01-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auxilio_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('administracao', 'Administração'), ('controle_ambiental', 'Controle Ambiental'), ('edificacoes', 'Edificações'), ('eletrotecnica', 'Eletrotécnica'), ('geologia', 'Geologia'), ('informatica_internet', 'Informática para Internet'), ('manutencao_suporte', 'Manutenção e Suporte em Informática'), ('mecanica', 'Mecânica'), ('mineracao', 'Mineração'), ('controle_ambiental_sub', 'Controle Ambiental (Subsequente)'), ('edificacoes_sub', 'Edificações (Subsequente)'), ('eletrotecnica_sub', 'Eletrotécnica (Subsequente)'), ('geologia_sub', 'Geologia (Subsequente)'), ('mecanica_sub', 'Mecânica (Subsequente)'), ('mineracao_sub', 'Mineração (Subsequente)'), ('petroleo_gas_sub', 'Petróleo e Gás (Subsequente)'), ('redes_comp_sub', 'Redes de Computadores (Subsequente)'), ('manutencao_suporte_sub', 'Manutenção e Suporte em Informática (Subsequente)'), ('informatica_sub', 'Informática (Subsequente)'), ('seguranca_trabalho_sub', 'Segurança do Trabalho (Subsequente)'), ('estradas_sub', 'Estradas (Subsequente)'), ('implanta_voip_fic', 'Implantação de Serviços VoIP (FIC)'), ('aplicador_ceramico_fic', 'Aplicador de Revestimento Cerâmico (FIC)'), ('artesanato_reciclavel_fic', 'Artesanato com Material Reciclável (FIC)'), ('engenharia_civil', 'Engenharia Civil'), ('engenharia_energia', 'Engenharia de Energia'), ('engenharia_sanitaria', 'Engenharia Sanitária e Ambiental'), ('tecnologia_ads', 'Tecnologia em Análise e Desenvolvimento de Sistemas'), ('tecnologia_com_exterior', 'Tecnologia em Comércio Exterior'), ('tecnologia_gestao_publica', 'Tecnologia em Gestão Pública'), ('tecnologia_redes_comp', 'Tecnologia em Redes de Computadores'), ('esp_seguranca_trab', 'Especialização em Engenharia de Segurança do Trabalho'), ('esp_ensino_geociencias', 'Especialização em Ensino de Geociências'), ('esp_gestao_ambiental', 'Especialização em Gestão Ambiental'), ('mestrado_prof_ensino_fis', 'Mestrado Profissional em Ensino de Física'), ('mestrado_prof_recursos_nat', 'Mestrado Profissional em Uso Sustentável de Recursos Naturais'), ('doutorado_educacao_prof', 'Doutorado Acadêmico em Educação Profissional')], default='', max_length=27)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.AlterField(
            model_name='auxilio',
            name='descricao',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='auxilio',
            name='nome',
            field=models.CharField(choices=[('Auxílio Transporte', 'auxilio_transporte'), ('Auxílio Moradia', 'auxilio_moradia'), ('Alimentação Estudantil', 'alimentacao_estudantil'), ('Apoio à Formação Estudantil', 'apoio_formacao_estudantil'), ('Auxílios Eventuais', 'auxilios_eventuais'), ('Outros', 'outros')], default='', max_length=27),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tipo_de_auxilio',
            field=models.CharField(choices=[('Auxílio Transporte', 'auxilio_transporte'), ('Auxílio Moradia', 'auxilio_moradia'), ('Alimentação Estudantil', 'alimentacao_estudantil'), ('Apoio à Formação Estudantil', 'apoio_formacao_estudantil'), ('Auxílios Eventuais', 'auxilios_eventuais'), ('Outros', 'outros')], default='auxilio transporte', max_length=30),
        ),
    ]
