# Generated by Django 5.0.7 on 2026-01-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_documento_chamado_chamado_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='documentos',
        ),
        migrations.AddField(
            model_name='chamado',
            name='documentos',
            field=models.ManyToManyField(null=True, to='api.documento', verbose_name='documentos'),
        ),
    ]
