# Generated by Django 5.0.7 on 2026-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_auxilio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='solicitados',
            field=models.CharField(choices=[('todos', 'Todos os alunos'), ('auxilio', 'Alunos do auxílio selecionado'), ('individual', 'Alunos selecionados individualmente')], default='todos', max_length=30),
        ),
    ]
