# Generated by Django 5.0.7 on 2026-06-13 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_auxilio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='solicitados',
            field=models.CharField(choices=[('todos', 'Todos os alunos'), ('auxilio', 'Alunos do auxílio selecionado'), ('individual', 'Alunos selecionados individualmente')], default='todos', max_length=30),
        ),
        migrations.CreateModel(
            name='Chamado_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='api.chamado')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chamado_chat',
                'ordering': ['data_envio'],
            },
        ),
    ]
