# Generated by Django 5.0.7 on 2026-06-22 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_chamado_justificativa_recusa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='justificativa_recusa',
        ),
    ]
