# Generated by Django 5.0.7 on 2026-06-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_chamado_justificativa_recusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='justificativa_chamado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
