# Generated by Django 5.0.7 on 2026-06-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_formulario_solicitados'),
        ('api', '0023_chamado_justificativa_chamado'),
    ]

    operations = [
    ]
